// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhmxebiqmmtakoknexuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpobXhlYmlxbW10YWtva25leHVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMDY5ODMsImV4cCI6MjA1ODY4Mjk4M30.v5_LaBq9wO3fsAgl_IXAJqbsi9DLqyTge4zyBJgtN50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);